meta_product_name: "App2Wait"
meta_title: "App2Wait - Enjoy your wait, create stories"
meta_description: "This app allows you to pick a challenge and send it to a person/group of people who are late. The challengee must then complete the challenge, while the challenger gets to record them and upload the video to the app."
meta_image: "logo.png" # should exist in `app/assets/images/`
